// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vOtoQwqkENrkWTdtgbUaSjDpgsTK5NM',
    appId: '1:201234155939:web:f5c3f34bc96954323e3216',
    messagingSenderId: '201234155939',
    projectId: 'koda-score-2',
    authDomain: 'koda-score-2.firebaseapp.com',
    storageBucket: 'koda-score-2.appspot.com',
    measurementId: 'G-3LXEWFWG0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApn5Oq9NLIJjoc2Dyi5i02NMF_iEO2YCM',
    appId: '1:201234155939:android:6d27c9a6039132d23e3216',
    messagingSenderId: '201234155939',
    projectId: 'koda-score-2',
    storageBucket: 'koda-score-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNBrGL2Z40QbEbhImW4so5RhC7hosBrg',
    appId: '1:201234155939:ios:dd5fb098b35534cc3e3216',
    messagingSenderId: '201234155939',
    projectId: 'koda-score-2',
    storageBucket: 'koda-score-2.appspot.com',
    iosClientId: '201234155939-7nhuqid6prjbak0jqf04pav7lrg32gfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.kodaNewRes',
  );
}
